-- Seed first-party MyPets evergreen BRL funds.

insert into public.causes (
  id, protector_id, slug, title, summary, story, country, city, primary_image,
  support_mode, target_amount_cents, raised_amount_cents, currency, status,
  is_public, published_at, vertical, campaign_key, campaign_meta,
  beneficiary_kind, fund_code, is_evergreen
) values
('9a7f1000-0000-4a11-8c01-000000000001'::uuid, null, 'mypets-geral-brl', 'Apoie o MyPets',
 'Apoio direto ao ecossistema MyPets para tecnologia, verificação, operação, atendimento, conteúdo e crescimento responsável.',
 'Fundo institucional do MyPets. O beneficiário é o próprio MyPets, e não uma causa externa específica.',
 'BR', null, 'https://res.cloudinary.com/fnki0ccg/image/upload/v1789145246/Logo_VPT.png',
 'FINANCIAL', null, 0, 'BRL', 'ACTIVE', true, now(), 'GENERAL', null,
 '{"beneficiaryLabel":"MyPets","trustNote":"Fundo institucional MyPets; não representa uma doação para uma causa externa específica."}'::jsonb,
 'MYPETS', 'GENERAL', true),
('9a7f1000-0000-4a11-8c01-000000000002'::uuid, null, 'mypets-vet-help-brl', 'Fundo MyPets Vet Help',
 'Apoio à frente MyPets dedicada a tratamentos veterinários e iniciativas verificadas deste ecossistema.',
 'O beneficiário é o MyPets. Os recursos são destinados à frente Vet Help e à capacidade de apoiar iniciativas elegíveis desta categoria.',
 'BR', null, 'https://mypets.lat/images/card-tratou.jpg', 'FINANCIAL', null, 0, 'BRL', 'ACTIVE', true, now(), 'VET', null,
 '{"beneficiaryLabel":"MyPets","trustNote":"Apoio à frente Vet Help; o beneficiário financeiro é o MyPets."}'::jsonb,
 'MYPETS', 'VET_HELP', true),
('9a7f1000-0000-4a11-8c01-000000000003'::uuid, null, 'mypets-rescue-brl', 'Fundo MyPets Rescue',
 'Apoio à frente MyPets dedicada a resgates urgentes e iniciativas verificadas deste ecossistema.',
 'O beneficiário é o MyPets. Os recursos são destinados à frente Rescue e à capacidade de apoiar iniciativas elegíveis desta categoria.',
 'BR', null, 'https://mypets.lat/images/card-resgatou.jpg', 'FINANCIAL', null, 0, 'BRL', 'ACTIVE', true, now(), 'RESCUE', null,
 '{"beneficiaryLabel":"MyPets","trustNote":"Apoio à frente Rescue; o beneficiário financeiro é o MyPets."}'::jsonb,
 'MYPETS', 'RESCUE', true),
('9a7f1000-0000-4a11-8c01-000000000004'::uuid, null, 'mypets-shelter-brl', 'Fundo MyPets Shelter',
 'Apoio à frente MyPets dedicada a abrigos, lares temporários e protetores.',
 'O beneficiário é o MyPets. Os recursos são destinados à frente Shelter e à capacidade de apoiar iniciativas elegíveis desta categoria.',
 'BR', null, 'https://mypets.lat/images/card-acolheu.jpg', 'FINANCIAL', null, 0, 'BRL', 'ACTIVE', true, now(), 'SHELTER', null,
 '{"beneficiaryLabel":"MyPets","trustNote":"Apoio à frente Shelter; o beneficiário financeiro é o MyPets."}'::jsonb,
 'MYPETS', 'SHELTER', true),
('9a7f1000-0000-4a11-8c01-000000000005'::uuid, null, 'mypets-emergency-brl', 'Fundo MyPets Emergency',
 'Apoio à frente MyPets dedicada a resposta rápida em catástrofes e emergências animais.',
 'O beneficiário é o MyPets. Os recursos são destinados à frente Emergency e à capacidade de apoiar iniciativas elegíveis desta categoria.',
 'BR', null, 'https://mypets.lat/images/cta-dog.jpg', 'FINANCIAL', null, 0, 'BRL', 'ACTIVE', true, now(), 'EMERGENCY', null,
 '{"beneficiaryLabel":"MyPets","trustNote":"Apoio à frente Emergency; o beneficiário financeiro é o MyPets."}'::jsonb,
 'MYPETS', 'EMERGENCY', true)
on conflict (slug) do update set
  title = excluded.title,
  summary = excluded.summary,
  story = excluded.story,
  primary_image = excluded.primary_image,
  support_mode = excluded.support_mode,
  currency = excluded.currency,
  status = excluded.status,
  is_public = excluded.is_public,
  vertical = excluded.vertical,
  campaign_meta = excluded.campaign_meta,
  beneficiary_kind = excluded.beneficiary_kind,
  fund_code = excluded.fund_code,
  is_evergreen = excluded.is_evergreen,
  updated_at = now();
